In [13]:
import pandas as pd
from functools import reduce

# 存储读取的数据DataFrame
df_population_density = pd.read_excel('人口密度.xlsx')
df_population_size = pd.read_excel('人口规模.xlsx')
df_urbanization_rate = pd.read_excel('城镇化率.xlsx')

employment_info_path = '就业信息.xlsx'
df_unemployment_rate = pd.read_excel(employment_info_path, '城镇失业率')
df_employment_number = pd.read_excel(employment_info_path, '从业人员数')
df_employment_industries = pd.read_excel(employment_info_path, '第一、二、三产业就业人数')

df_salary_level = pd.read_excel('工资水平.xlsx')
df_age_structure = pd.read_excel('年龄结构.xlsx').rename(columns={'城市': '城市名称'})

life_path = '生活水平.xlsx'
life_avg_in = pd.read_excel(life_path, '人均可支配收入', header=1)
life_avg_out = pd.read_excel(life_path, '人均消费支出', header=1)
life_urban_avg_in = pd.read_excel(life_path, '城镇居民人均收入', header=1)
life_urban_avg_out = pd.read_excel(life_path, '城镇居民消费支出', header=1)
life_rural_avg_in = pd.read_excel(life_path, '农村居民人均收入', header=1)
life_rural_avg_out = pd.read_excel(life_path, '农村居民消费支出', header=1)

# 数据结构转换
df_salary_level = pd.melt(df_salary_level, id_vars=['averageWage'], var_name='城市名称', value_name='平均收入')
df_salary_level.columns = ['年份', '城市名称', '平均收入']
df_salary_level['年份'] = df_salary_level['年份'].str.replace('年', '').astype('int64')
life_avg_in = pd.melt(life_avg_in, id_vars=['城市名称'], var_name='年份', value_name='人均可支配收入')
life_avg_in.columns = ['城市名称', '年份', '人均可支配收入']
life_avg_out = pd.melt(life_avg_out, id_vars=['城市名称'], var_name='年份', value_name='人均消费支出')
life_avg_out.columns = ['城市名称', '年份', '人均消费支出']
life_urban_avg_in = pd.melt(life_urban_avg_in, id_vars=['城市名称'], var_name='年份', value_name='城镇居民人均收入')
life_urban_avg_in.columns = ['城市名称', '年份', '城镇居民人均收入']
life_urban_avg_out = pd.melt(life_urban_avg_out, id_vars=['城市名称'], var_name='年份', value_name='城镇居民消费支出')
life_urban_avg_out.columns = ['城市名称', '年份', '城镇居民消费支出']
life_rural_avg_in = pd.melt(life_rural_avg_in, id_vars=['城市名称'], var_name='年份', value_name='农村居民人均收入')
life_rural_avg_in.columns = ['城市名称', '年份', '农村居民人均收入']
life_rural_avg_out = pd.melt(life_rural_avg_out, id_vars=['城市名称'], var_name='年份', value_name='农村居民消费支出')
life_rural_avg_out.columns = ['城市名称', '年份', '农村居民消费支出']


print("人口密度:")
print(df_population_density)

print("人口规模:")
print(df_population_size)

print("城镇化率:")
print(df_urbanization_rate)

print("城镇失业率:")
print(df_unemployment_rate)

print("从业人员数:")
print(df_employment_number)

print("第一、二、三产业就业人数:")
print(df_employment_industries)

print("工资水平:")
print(df_salary_level)

print("年龄结构:")
print(df_age_structure)

print("人均可支配收入:")
print(life_avg_in)

print("人均消费支出:")
print(life_avg_out)

print("城镇居民人均收入:")
print(life_urban_avg_in)

print("城镇居民消费支出:")
print(life_urban_avg_out)

print("农村居民人均收入:")
print(life_rural_avg_in)

print("农村居民消费支出:")
print(life_rural_avg_out)

dfs = [df_population_density, df_population_size, df_urbanization_rate, df_unemployment_rate, df_employment_number,
       df_employment_industries, df_salary_level, df_age_structure, life_avg_in, life_avg_out, life_urban_avg_in,
       life_urban_avg_out, life_rural_avg_in, life_rural_avg_out]
merged_df = reduce(lambda left, right: pd.merge(left, right, on=['城市名称', '年份'], how='outer'), dfs)
print(merged_df)
merged_df.to_excel('merged_file.xlsx', index=False)

人口密度:
       年份    城市名称  人口密度（人/平方公里）
0    2022   city1           588
1    2021   city1           587
2    2020   city1           581
3    2019   city1           528
4    2018   city1           522
..    ...     ...           ...
753  2022  city29           660
754  2022  city24          1167
755  2022  city28           909
756  2022  city32           789
757  2022  city36           844

[758 rows x 3 columns]
人口规模:
       城市名称    年份  常住人口（万人）  户籍人口（万人）
0     city1  2021     337.0     268.0
1     city1  2020     306.0     268.0
2     city1  2019     303.0     267.0
3     city1  2018     300.0     266.0
4     city1  2017     298.0     265.0
..      ...   ...       ...       ...
713  city40  2010     307.0     270.0
714  city40  2009     304.0     269.0
715  city40  2008     302.0     269.0
716  city40  2007     300.0     269.0
717  city40  2001     284.0       NaN

[718 rows x 4 columns]
城镇化率:
       城市名称    年份  urbanizationRate
0     city1  2007                48
1     city1  2008                49
2     city1  2009                50
3     city1  2010                51
4     city1  2011                53
..      ...   ...               ...
670  city40  2010                62
671  city40  2009                60
672  city40  2008                60
673  city40  2007                60
674  city40  2006                59

[675 rows x 3 columns]
城镇失业率:
       年份    城市名称  unemploymentRate
0    2001   city1               3.0
1    2002   city1               4.0
2    2003   city1               4.0
3    2005   city1               4.0
4    2006   city1               4.0
..    ...     ...               ...
764  2018  city40               2.0
765  2019  city40               2.0
766  2020  city40               2.0
767  2021  city40               2.0
768  2022  city40               3.0

[769 rows x 3 columns]
从业人员数:
       城市名称    年份  employeesNumber
0     city1  2021              199
1     city1  2019              194
2     city1  2018              192
3     city1  2017              189
4     city1  2016              187
..      ...   ...              ...
757  city39  2017              151
758  city39  2018              143
759  city39  2019              133
760  city39  2020              130
761  city39  2021              124

[762 rows x 3 columns]
第一、二、三产业就业人数:
       城市名称    年份  pi_Employment  si_Employment  ti_Employment
0     city1  2021              0            101             89
1     city1  2019              0             95             79
2     city1  2018              0             96             74
3     city1  2017              0             96             72
4     city1  2016              0             96             69
..      ...   ...            ...            ...            ...
693  city40  2007             33             75             46
694  city40  2006             35             68             45
695  city40  2005             37             63             45
696  city40  2004             39             60             41
697  city40  2003             44             55             42

[698 rows x 5 columns]
工资水平:
       年份    城市名称     平均收入
0    2001   city1  10340.0
1    2002   city1  13044.0
2    2003   city1  16648.0
3    2004   city1  19968.0
4    2005   city1  22024.0
..    ...     ...      ...
835  2017  city40  68872.0
836  2018  city40  75312.0
837  2019  city40  79608.0
838  2020  city40  87012.0
839  2021  city40  93128.0

[840 rows x 3 columns]
年龄结构:
       城市名称    年份  0-14  15-64   65+
0     city1  2020    40  225.0  72.0
1     city1  2010    34  209.0  47.0
2     city1  2000    49  178.0  36.0
3    city10  2020    40  157.0  53.0
4    city10  2010    36  141.0  38.0
..      ...   ...   ...    ...   ...
113  city39  2010    32  142.0  18.0
114  city39  2000    36    NaN  11.0
115  city40  2020    38  207.0  76.0
116  city40  2010    32  229.0  51.0
117  city40  2000    48    NaN   NaN

[118 rows x 5 columns]
人均可支配收入:
       城市名称    年份  人均可支配收入
0     city3  2015    40948
1     city6  2015    35140
2    city14  2015    13280
3     city9  2015    15264
4    city11  2015    34316
..      ...   ...      ...
171  city38  2022    30392
172  city21  2022    67708
173  city25  2022    65436
174  city29  2022    55496
175  city33  2022    59588

[176 rows x 3 columns]
人均消费支出:
       城市名称    年份  人均消费支出
0     city3  2015   28852
1     city6  2015   24848
2    city14  2015    9976
3     city9  2015   11236
4    city11  2015   20304
..      ...   ...     ...
179  city38  2022   19092
180  city21  2022  446007
181  city25  2022   40476
182  city29  2022   36225
183  city33  2022   39900

[184 rows x 3 columns]
城镇居民人均收入:
       城市名称    年份  城镇居民人均收入
0     city3  2011   36505.0
1     city6  2011   30715.0
2    city14  2011   14735.0
3     city9  2011   16110.0
4     city1  2011       NaN
..      ...   ...       ...
391  city28  2022   60237.0
392  city24  2022   57447.0
393  city32  2022   50094.0
394  city36  2022   37842.0
395  city39  2022   56625.0

[396 rows x 3 columns]
城镇居民消费支出:
       城市名称    年份  城镇居民消费支出
0     city3  2011   22804.0
1     city6  2011   21992.0
2    city14  2011    8368.0
3     city9  2011   10180.0
4     city1  2011       NaN
..      ...   ...       ...
331  city24  2022   36864.0
332  city28  2022   38571.0
333  city32  2022   31674.0
334  city36  2022   22029.0
335  city39  2022   33525.0

[336 rows x 3 columns]
农村居民人均收入:
       城市名称    年份  农村居民人均收入
0     city6  2011   13860.0
1    city14  2011    6732.0
2     city9  2011    8188.0
3     city1  2011       NaN
4     city4  2011       NaN
..      ...   ...       ...
331  city25  2022   65436.0
332  city29  2022   55497.0
333  city33  2022   59586.0
334  city22  2022   32700.0
335  city30  2022   21372.0

[336 rows x 3 columns]
农村居民消费支出:
       城市名称    年份  农村居民消费支出
0     city6  2011   11184.0
1    city14  2011    5880.0
2     city9  2011    5584.0
3     city1  2011       NaN
4     city4  2011       NaN
..      ...   ...       ...
259  city38  2022   14997.0
260  city21  2022   30222.0
261  city25  2022   27450.0
262  city29  2022   26838.0
263  city22  2022   24006.0

[264 rows x 3 columns]
        年份    城市名称  人口密度（人/平方公里）  常住人口（万人）  户籍人口（万人）  urbanizationRate
0     2022   city1         588.0       NaN       NaN              66.0  \
1     2021   city1         587.0     337.0     268.0              66.0
2     2020   city1         581.0     306.0     268.0              65.0
3     2019   city1         528.0     303.0     267.0              64.0
4     2018   city1         522.0     300.0     266.0              62.0
...    ...     ...           ...       ...       ...               ...
1029  2021  ctiy22           NaN       NaN       NaN               NaN
1030  2022  ctiy31           NaN       NaN       NaN               NaN
1031  2022  ctiy22           NaN       NaN       NaN               NaN
1032  2022  city30           NaN       NaN       NaN               NaN
1033  2022  city22           NaN       NaN       NaN               NaN

      unemploymentRate  employeesNumber  pi_Employment  si_Employment  ...
0                  NaN              NaN            NaN            NaN  ...  \
1                  2.0            199.0            0.0          101.0  ...
2                  2.0              NaN            NaN            NaN  ...
3                  2.0            194.0            0.0           95.0  ...
4                  2.0            192.0            0.0           96.0  ...
...                ...              ...            ...            ...  ...
1029               NaN              NaN            NaN            NaN  ...
1030               NaN              NaN            NaN            NaN  ...
1031               NaN              NaN            NaN            NaN  ...
1032               NaN              NaN            NaN            NaN  ...
1033               NaN              NaN            NaN            NaN  ...

         平均收入  0-14  15-64   65+  人均可支配收入   人均消费支出  城镇居民人均收入  城镇居民消费支出
0         NaN   NaN    NaN   NaN  57492.0  35870.0   71040.0   41532.0  \
1     97620.0   NaN    NaN   NaN  51800.0  30412.0   67980.0   35488.0
2         NaN  40.0  225.0  72.0  48672.0  29656.0   61740.0   34916.0
3     81616.0   NaN    NaN   NaN  44484.0  26964.0   59025.0   31828.0
4     72332.0   NaN    NaN   NaN  40700.0  24420.0   54390.0   28960.0
...       ...   ...    ...   ...      ...      ...       ...       ...
1029      NaN   NaN    NaN   NaN      NaN      NaN   67551.0       NaN
1030      NaN   NaN    NaN   NaN      NaN      NaN   43620.0       NaN
1031      NaN   NaN    NaN   NaN      NaN      NaN   73593.0       NaN
1032      NaN   NaN    NaN   NaN      NaN      NaN   39861.0       NaN
1033      NaN   NaN    NaN   NaN      NaN      NaN       NaN   42486.0

      农村居民人均收入  农村居民消费支出
0      44112.0   29356.0
1      41300.0   27132.0
2      37244.0   22984.0
3      34800.0   22612.0
4      31764.0   20716.0
...        ...       ...
1029       NaN       NaN
1030       NaN       NaN
1031       NaN       NaN
1032   21372.0       NaN
1033   32700.0   24006.0

[1034 rows x 21 columns]